name: Basic bun tests

on:
  pull_request:
    branches: [main]


jobs:
  basic-tests:
    name: Basic Tests (No Secrets)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or specify a version
      - name: Install dependencies
        run: bun install
