name: CI with Bun Test

on:
  pull_request:
    branches: [main]

  pull_request_review:
    types: [approved]

jobs:
  basic-tests:
    name: Basic Tests (No Secrets)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or specify a version
      - name: Install dependencies
        run: bun install


  full-tests:
    name: Full Tests (On Approval)
    runs-on: ubuntu-latest
    needs: basic-tests
    if: github.event.review.state == 'approved'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0 # Important for git revert
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run full tests
        run: bun test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }} # Access your secrets here
      - name: Revert commit on failure
        if: failure()
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git revert ${{ github.event.pull_request.merge_commit_sha }} --no-edit
          git push origin HEAD:${{ github.event.pull_request.head.ref }} -f
      - name: Comment on PR
        if: failure()
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The full test suite failed. The merge has been reverted. Please address the issues and try again.
