# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug Environment Variables (Existence Check)
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: |
          if [ -n "$BOT_TOKEN" ]; then
            echo "BOT_TOKEN is set"
          else
            echo "BOT_TOKEN is NOT set"
          fi
          if [ -n "$CLIENT_ID" ]; then
            echo "CLIENT_ID is set"
          else
            echo "CLIENT_ID is NOT set"
          fi
        
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies # (assuming your project has dependencies)
        run: bun install # You can use npm/yarn/pnpm instead if you prefer
      - name: Run tests
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: bun test
