name: CI with Bun Test

on:
  workflow_run:
    workflows: ["Basic bun tests"]
    types:
      - completed

jobs:

  full-tests:
    name: Full Tests (On Approval)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
          repository: ${{ github.event.workflow_run.pull_requests[0].head.repo.full_name }}
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run full tests
        run: bun test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }} # Access your secrets here
      - name: Request changes if tests fail
        if: failure()
        run: gh pr review ${{ github.event.workflow_run.pull_requests[0].number }} --request-changes --body "Tests failed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
